// Generated by scripts/fetch-app-data.mjs. Do not edit by hand.
export const NIGHTLY_RELEASE = {
  "tag": "nightly-20260912-1bae5d7",
  "name": "Nightly (v0.23.1-2)",
  "version": "0.23.1",
  "publishedAt": "2026-09-12T07:49:50Z",
  "url": "https://github.com/TabularisDB/tabularis/releases/tag/nightly-20260912-1bae5d7",
  "assets": [
    {
      "name": "latest.json",
      "url": "https://github.com/TabularisDB/tabularis/releases/download/nightly-20260912-1bae5d7/latest.json"
    },
    {
      "name": "tabularis-0.23.1-2-1.x86_64.rpm",
      "url": "https://github.com/TabularisDB/tabularis/releases/download/nightly-20260912-1bae5d7/tabularis-0.23.1-2-1.x86_64.rpm"
    },
    {
      "name": "tabularis-0.23.1-2-1.x86_64.rpm.sig",
      "url": "https://github.com/TabularisDB/tabularis/releases/download/nightly-20260912-1bae5d7/tabularis-0.23.1-2-1.x86_64.rpm.sig"
    },
    {
      "name": "tabularis_0.23.1-2_aarch64.app.tar.gz",
      "url": "https://github.com/TabularisDB/tabularis/releases/download/nightly-20260912-1bae5d7/tabularis_0.23.1-2_aarch64.app.tar.gz"
    },
    {
      "name": "tabularis_0.23.1-2_aarch64.app.tar.gz.sig",
      "url": "https://github.com/TabularisDB/tabularis/releases/download/nightly-20260912-1bae5d7/tabularis_0.23.1-2_aarch64.app.tar.gz.sig"
    },
    {
      "name": "tabularis_0.23.1-2_aarch64.dmg",
      "url": "https://github.com/TabularisDB/tabularis/releases/download/nightly-20260912-1bae5d7/tabularis_0.23.1-2_aarch64.dmg"
    },
    {
      "name": "tabularis_0.23.1-2_amd64.AppImage",
      "url": "https://github.com/TabularisDB/tabularis/releases/download/nightly-20260912-1bae5d7/tabularis_0.23.1-2_amd64.AppImage"
    },
    {
      "name": "tabularis_0.23.1-2_amd64.AppImage.sig",
      "url": "https://github.com/TabularisDB/tabularis/releases/download/nightly-20260912-1bae5d7/tabularis_0.23.1-2_amd64.AppImage.sig"
    },
    {
      "name": "tabularis_0.23.1-2_amd64.deb",
      "url": "https://github.com/TabularisDB/tabularis/releases/download/nightly-20260912-1bae5d7/tabularis_0.23.1-2_amd64.deb"
    },
    {
      "name": "tabularis_0.23.1-2_amd64.deb.sig",
      "url": "https://github.com/TabularisDB/tabularis/releases/download/nightly-20260912-1bae5d7/tabularis_0.23.1-2_amd64.deb.sig"
    },
    {
      "name": "tabularis_0.23.1-2_x64-setup.exe",
      "url": "https://github.com/TabularisDB/tabularis/releases/download/nightly-20260912-1bae5d7/tabularis_0.23.1-2_x64-setup.exe"
    },
    {
      "name": "tabularis_0.23.1-2_x64-setup.exe.sig",
      "url": "https://github.com/TabularisDB/tabularis/releases/download/nightly-20260912-1bae5d7/tabularis_0.23.1-2_x64-setup.exe.sig"
    },
    {
      "name": "tabularis_0.23.1-2_x64.app.tar.gz",
      "url": "https://github.com/TabularisDB/tabularis/releases/download/nightly-20260912-1bae5d7/tabularis_0.23.1-2_x64.app.tar.gz"
    },
    {
      "name": "tabularis_0.23.1-2_x64.app.tar.gz.sig",
      "url": "https://github.com/TabularisDB/tabularis/releases/download/nightly-20260912-1bae5d7/tabularis_0.23.1-2_x64.app.tar.gz.sig"
    },
    {
      "name": "tabularis_0.23.1-2_x64.dmg",
      "url": "https://github.com/TabularisDB/tabularis/releases/download/nightly-20260912-1bae5d7/tabularis_0.23.1-2_x64.dmg"
    },
    {
      "name": "tabularis_0.23.1-2_x64_en-US.msi",
      "url": "https://github.com/TabularisDB/tabularis/releases/download/nightly-20260912-1bae5d7/tabularis_0.23.1-2_x64_en-US.msi"
    },
    {
      "name": "tabularis_0.23.1-2_x64_en-US.msi.sig",
      "url": "https://github.com/TabularisDB/tabularis/releases/download/nightly-20260912-1bae5d7/tabularis_0.23.1-2_x64_en-US.msi.sig"
    },
    {
      "name": "tabularis_nightly-20260912-1bae5d7_x64-portable.exe",
      "url": "https://github.com/TabularisDB/tabularis/releases/download/nightly-20260912-1bae5d7/tabularis_nightly-20260912-1bae5d7_x64-portable.exe"
    }
  ]
} as const;
