// Generated by scripts/fetch-app-data.mjs. Do not edit by hand.
export const NIGHTLY_RELEASE = {
  "tag": "nightly-20260825-cb276c8",
  "name": "Nightly (v0.20.1-6)",
  "version": "0.20.1",
  "publishedAt": "2026-08-25T03:58:49Z",
  "url": "https://github.com/TabularisDB/tabularis/releases/tag/nightly-20260825-cb276c8",
  "assets": [
    {
      "name": "latest.json",
      "url": "https://github.com/TabularisDB/tabularis/releases/download/nightly-20260825-cb276c8/latest.json"
    },
    {
      "name": "tabularis-0.20.1-6-1.x86_64.rpm",
      "url": "https://github.com/TabularisDB/tabularis/releases/download/nightly-20260825-cb276c8/tabularis-0.20.1-6-1.x86_64.rpm"
    },
    {
      "name": "tabularis-0.20.1-6-1.x86_64.rpm.sig",
      "url": "https://github.com/TabularisDB/tabularis/releases/download/nightly-20260825-cb276c8/tabularis-0.20.1-6-1.x86_64.rpm.sig"
    },
    {
      "name": "tabularis_0.20.1-6_aarch64.app.tar.gz",
      "url": "https://github.com/TabularisDB/tabularis/releases/download/nightly-20260825-cb276c8/tabularis_0.20.1-6_aarch64.app.tar.gz"
    },
    {
      "name": "tabularis_0.20.1-6_aarch64.app.tar.gz.sig",
      "url": "https://github.com/TabularisDB/tabularis/releases/download/nightly-20260825-cb276c8/tabularis_0.20.1-6_aarch64.app.tar.gz.sig"
    },
    {
      "name": "tabularis_0.20.1-6_aarch64.dmg",
      "url": "https://github.com/TabularisDB/tabularis/releases/download/nightly-20260825-cb276c8/tabularis_0.20.1-6_aarch64.dmg"
    },
    {
      "name": "tabularis_0.20.1-6_amd64.AppImage",
      "url": "https://github.com/TabularisDB/tabularis/releases/download/nightly-20260825-cb276c8/tabularis_0.20.1-6_amd64.AppImage"
    },
    {
      "name": "tabularis_0.20.1-6_amd64.AppImage.sig",
      "url": "https://github.com/TabularisDB/tabularis/releases/download/nightly-20260825-cb276c8/tabularis_0.20.1-6_amd64.AppImage.sig"
    },
    {
      "name": "tabularis_0.20.1-6_amd64.deb",
      "url": "https://github.com/TabularisDB/tabularis/releases/download/nightly-20260825-cb276c8/tabularis_0.20.1-6_amd64.deb"
    },
    {
      "name": "tabularis_0.20.1-6_amd64.deb.sig",
      "url": "https://github.com/TabularisDB/tabularis/releases/download/nightly-20260825-cb276c8/tabularis_0.20.1-6_amd64.deb.sig"
    },
    {
      "name": "tabularis_0.20.1-6_x64-setup.exe",
      "url": "https://github.com/TabularisDB/tabularis/releases/download/nightly-20260825-cb276c8/tabularis_0.20.1-6_x64-setup.exe"
    },
    {
      "name": "tabularis_0.20.1-6_x64-setup.exe.sig",
      "url": "https://github.com/TabularisDB/tabularis/releases/download/nightly-20260825-cb276c8/tabularis_0.20.1-6_x64-setup.exe.sig"
    },
    {
      "name": "tabularis_0.20.1-6_x64.app.tar.gz",
      "url": "https://github.com/TabularisDB/tabularis/releases/download/nightly-20260825-cb276c8/tabularis_0.20.1-6_x64.app.tar.gz"
    },
    {
      "name": "tabularis_0.20.1-6_x64.app.tar.gz.sig",
      "url": "https://github.com/TabularisDB/tabularis/releases/download/nightly-20260825-cb276c8/tabularis_0.20.1-6_x64.app.tar.gz.sig"
    },
    {
      "name": "tabularis_0.20.1-6_x64.dmg",
      "url": "https://github.com/TabularisDB/tabularis/releases/download/nightly-20260825-cb276c8/tabularis_0.20.1-6_x64.dmg"
    },
    {
      "name": "tabularis_0.20.1-6_x64_en-US.msi",
      "url": "https://github.com/TabularisDB/tabularis/releases/download/nightly-20260825-cb276c8/tabularis_0.20.1-6_x64_en-US.msi"
    },
    {
      "name": "tabularis_0.20.1-6_x64_en-US.msi.sig",
      "url": "https://github.com/TabularisDB/tabularis/releases/download/nightly-20260825-cb276c8/tabularis_0.20.1-6_x64_en-US.msi.sig"
    },
    {
      "name": "tabularis_nightly-20260825-cb276c8_x64-portable.exe",
      "url": "https://github.com/TabularisDB/tabularis/releases/download/nightly-20260825-cb276c8/tabularis_nightly-20260825-cb276c8_x64-portable.exe"
    }
  ]
} as const;
