// Generated by scripts/fetch-app-data.mjs. Do not edit by hand.
export interface NightlyReleaseAsset {
    name: string;
    url: string;
}

export interface NightlyRelease {
    tag: string;
    name: string;
    version: string | null;
    publishedAt: string;
    url: string;
    assets: NightlyReleaseAsset[];
}

export const NIGHTLY_RELEASE: NightlyRelease = {
  "tag": "nightly-20261002-b78a409",
  "name": "Nightly (v0.26.1-1)",
  "version": "0.26.1",
  "publishedAt": "2026-10-02T09:33:41Z",
  "url": "https://github.com/TabularisDB/tabularis/releases/tag/nightly-20261002-b78a409",
  "assets": [
    {
      "name": "latest.json",
      "url": "https://github.com/TabularisDB/tabularis/releases/download/nightly-20261002-b78a409/latest.json"
    },
    {
      "name": "tabularis-0.26.1-1-1.x86_64.rpm",
      "url": "https://github.com/TabularisDB/tabularis/releases/download/nightly-20261002-b78a409/tabularis-0.26.1-1-1.x86_64.rpm"
    },
    {
      "name": "tabularis-0.26.1-1-1.x86_64.rpm.sig",
      "url": "https://github.com/TabularisDB/tabularis/releases/download/nightly-20261002-b78a409/tabularis-0.26.1-1-1.x86_64.rpm.sig"
    },
    {
      "name": "tabularis_0.26.1-1_aarch64.app.tar.gz",
      "url": "https://github.com/TabularisDB/tabularis/releases/download/nightly-20261002-b78a409/tabularis_0.26.1-1_aarch64.app.tar.gz"
    },
    {
      "name": "tabularis_0.26.1-1_aarch64.app.tar.gz.sig",
      "url": "https://github.com/TabularisDB/tabularis/releases/download/nightly-20261002-b78a409/tabularis_0.26.1-1_aarch64.app.tar.gz.sig"
    },
    {
      "name": "tabularis_0.26.1-1_aarch64.dmg",
      "url": "https://github.com/TabularisDB/tabularis/releases/download/nightly-20261002-b78a409/tabularis_0.26.1-1_aarch64.dmg"
    },
    {
      "name": "tabularis_0.26.1-1_amd64.AppImage",
      "url": "https://github.com/TabularisDB/tabularis/releases/download/nightly-20261002-b78a409/tabularis_0.26.1-1_amd64.AppImage"
    },
    {
      "name": "tabularis_0.26.1-1_amd64.AppImage.sig",
      "url": "https://github.com/TabularisDB/tabularis/releases/download/nightly-20261002-b78a409/tabularis_0.26.1-1_amd64.AppImage.sig"
    },
    {
      "name": "tabularis_0.26.1-1_amd64.deb",
      "url": "https://github.com/TabularisDB/tabularis/releases/download/nightly-20261002-b78a409/tabularis_0.26.1-1_amd64.deb"
    },
    {
      "name": "tabularis_0.26.1-1_amd64.deb.sig",
      "url": "https://github.com/TabularisDB/tabularis/releases/download/nightly-20261002-b78a409/tabularis_0.26.1-1_amd64.deb.sig"
    },
    {
      "name": "tabularis_0.26.1-1_x64-setup.exe",
      "url": "https://github.com/TabularisDB/tabularis/releases/download/nightly-20261002-b78a409/tabularis_0.26.1-1_x64-setup.exe"
    },
    {
      "name": "tabularis_0.26.1-1_x64-setup.exe.sig",
      "url": "https://github.com/TabularisDB/tabularis/releases/download/nightly-20261002-b78a409/tabularis_0.26.1-1_x64-setup.exe.sig"
    },
    {
      "name": "tabularis_0.26.1-1_x64.app.tar.gz",
      "url": "https://github.com/TabularisDB/tabularis/releases/download/nightly-20261002-b78a409/tabularis_0.26.1-1_x64.app.tar.gz"
    },
    {
      "name": "tabularis_0.26.1-1_x64.app.tar.gz.sig",
      "url": "https://github.com/TabularisDB/tabularis/releases/download/nightly-20261002-b78a409/tabularis_0.26.1-1_x64.app.tar.gz.sig"
    },
    {
      "name": "tabularis_0.26.1-1_x64.dmg",
      "url": "https://github.com/TabularisDB/tabularis/releases/download/nightly-20261002-b78a409/tabularis_0.26.1-1_x64.dmg"
    },
    {
      "name": "tabularis_0.26.1-1_x64_en-US.msi",
      "url": "https://github.com/TabularisDB/tabularis/releases/download/nightly-20261002-b78a409/tabularis_0.26.1-1_x64_en-US.msi"
    },
    {
      "name": "tabularis_0.26.1-1_x64_en-US.msi.sig",
      "url": "https://github.com/TabularisDB/tabularis/releases/download/nightly-20261002-b78a409/tabularis_0.26.1-1_x64_en-US.msi.sig"
    },
    {
      "name": "tabularis_nightly-20261002-b78a409_x64-portable.exe",
      "url": "https://github.com/TabularisDB/tabularis/releases/download/nightly-20261002-b78a409/tabularis_nightly-20261002-b78a409_x64-portable.exe"
    }
  ]
} as const;
