import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { JsonLd } from "@/components/JsonLd";
import { SiteHeader } from "@/components/SiteHeader";
import { Footer } from "@/components/Footer";
import { ClosingCta } from "@/components/ClosingCta";
import { CtaSocialLinks } from "@/components/CtaSocialLinks";
import { PostContentLightbox } from "@/components/PostContentLightbox";
import { PostSideRail } from "@/components/PostSideRail";
import {
  getAllPosts,
  getPostBySlug,
  getAdjacentPosts,
  postOgImage,
} from "@/lib/posts";
import {
  resolveAuthors,
  authorAvatarUrl,
  authorGitHubUrl,
} from "@/lib/authors";
import { PostByline } from "@/components/PostByline";
import { NewsletterForm } from "@/components/NewsletterForm";
import { PostNewsletterSlots } from "@/components/PostNewsletterSlots";
import { buildArticleJsonLd, buildBreadcrumbJsonLd } from "@/lib/seo";
import { getRelatedLinksForPost } from "@/lib/seoRelated";
import { RelatedLinks } from "@/components/RelatedLinks";

interface PageProps {
  params: Promise<{ slug: string }>;
}

export function generateStaticParams() {
  return getAllPosts().map((p) => ({ slug: p.slug }));
}

export async function generateMetadata({
  params,
}: PageProps): Promise<Metadata> {
  const { slug } = await params;
  const post = await getPostBySlug(slug);
  if (!post) return {};

  const { meta } = post;
  // Always emit an og:image: a post's ready-made cover when it ships one,
  // otherwise the per-post card generated by blog/[slug]/opengraph-image.tsx.
  // Both point at a real `.png` asset (the extension-less convention route is
  // served as application/octet-stream by static hosts, which link-card
  // scrapers like Bluesky's CardyB reject); scripts/finalize-og-images.mjs
  // renames the generated card to `.png` at the end of the build. We set
  // `images` explicitly because handing Next an `openGraph` block without it
  // suppresses the automatic file-convention fallback, leaving no og:image.
  const ogImageUrl = meta.og?.cover
    ? `https://tabularis.dev${meta.og.cover}`
    : `https://tabularis.dev${postOgImage(slug)}`;
  const coverImages = [
    {
      url: ogImageUrl,
      width: 1200,
      height: 630,
      alt: meta.title,
    },
  ];
  return {
    title: `${meta.title} | Tabularis Blog`,
    description: meta.excerpt,
    openGraph: {
      type: "article",
      url: `https://tabularis.dev/blog/${slug}`,
      title: `${meta.title} | Tabularis Blog`,
      description: meta.excerpt,
      siteName: "Tabularis Blog",
      images: coverImages,
    },
    twitter: {
      card: "summary_large_image",
      images: coverImages,
      title: `${meta.title} | Tabularis Blog`,
      description: meta.excerpt,
    },
  };
}

export default async function BlogPostPage({ params }: PageProps) {
  const { slug } = await params;
  const post = await getPostBySlug(slug);
  if (!post) notFound();

  const { meta, html } = post;

  const h1End = html.indexOf("</h1>");
  const htmlBefore = h1End >= 0 ? html.slice(0, h1End + 5) : html;
  const htmlAfter = h1End >= 0 ? html.slice(h1End + 5) : "";

  const { prev, next } = getAdjacentPosts(slug);
  const relatedLinks = getRelatedLinksForPost(meta.tags);
  const authors = resolveAuthors(meta.authors);

  const crumbTitle =
    meta.title.length > 40 ? meta.title.slice(0, 40) + "…" : meta.title;

  return (
    <div className="container">
      <JsonLd
        data={[
          buildBreadcrumbJsonLd([
            { name: "Home", path: "/" },
            { name: "Blog", path: "/blog" },
            { name: meta.title, path: `/blog/${slug}` },
          ]),
          buildArticleJsonLd({
            title: meta.title,
            description: meta.excerpt,
            path: `/blog/${slug}`,
            publishedTime: meta.date,
            image: meta.og?.image,
            authors: authors.map((a) => ({
              name: a.name,
              url: authorGitHubUrl(a.github),
            })),
          }),
        ]}
      />
      <SiteHeader
        crumbs={[{ label: "blog", href: "/blog" }, { label: crumbTitle }]}
      />

      <article className="post-content post-layout">
        <header className="post-header">
          {meta.tags && meta.tags.length > 0 && (
            <div className="post-eyebrow">
              {meta.tags.map((t) => (
                <Link key={t} href={`/blog/tag/${t}`} className="post-eyebrow-tag">
                  {t}
                </Link>
              ))}
            </div>
          )}
          {htmlBefore && (
            <div
              className="post-header-title"
              dangerouslySetInnerHTML={{ __html: htmlBefore }}
            />
          )}
          <PostByline
            authors={meta.authors}
            date={meta.date}
            readingTime={meta.readingTime}
            release={meta.release}
          />
        </header>
        {htmlAfter && (
          <div
            className="post-body"
            dangerouslySetInnerHTML={{ __html: htmlAfter }}
          />
        )}
        <PostSideRail title={meta.title} url={`/blog/${slug}`} />
      </article>
      <PostNewsletterSlots />
      <PostContentLightbox />

      <RelatedLinks title="Related Guides" links={relatedLinks} />

      <ClosingCta
        title="Enjoyed this post? Try Tabularis."
        lede="Free and open source (Apache 2.0). Download it for Windows, macOS, or Linux — and if you like what you read, a star on GitHub helps more developers discover it."
        showVideo
      >
        <CtaSocialLinks />
      </ClosingCta>

      <NewsletterForm compact />

      {authors.map((author) => (
        <div className="post-author" key={author.handle}>
          <img
            src={authorAvatarUrl(author.github)}
            alt={author.name}
            className="post-author-avatar"
          />
          <div className="post-author-info">
            <span className="post-author-name">
              <Link href={`/blog/author/${author.handle}`}>{author.name}</Link>
            </span>
            <span className="post-author-bio">
              {author.bio}{" "}
              <a
                href={authorGitHubUrl(author.github)}
                target="_blank"
                rel="noopener noreferrer"
              >
                @{author.github}
              </a>
            </span>
          </div>
        </div>
      ))}

      <nav className="post-nav">
        <div className="post-nav-item post-nav-prev">
          {prev ? (
            <Link href={`/blog/${prev.slug}`}>
              <span className="post-nav-label">← Newer</span>
              <span className="post-nav-title">{prev.title}</span>
            </Link>
          ) : (
            <span className="post-nav-empty" />
          )}
        </div>
        <div className="post-nav-item post-nav-next">
          {next ? (
            <Link href={`/blog/${next.slug}`}>
              <span className="post-nav-label">Older →</span>
              <span className="post-nav-title">{next.title}</span>
            </Link>
          ) : (
            <span className="post-nav-empty" />
          )}
        </div>
      </nav>

      <Footer />
    </div>
  );
}
