// Generated by scripts/fetch-app-data.mjs. Do not edit by hand.
import type {CommunityIssue} from './types';

export const ISSUES_ORG = "TabularisDB";
export const FEATURED_LABELS = ["good first issue","help wanted"];
export const ISSUES_FETCHED_AT = "2026-10-07T21:41:08.632Z";
export const COMMUNITY_ISSUES: CommunityIssue[] = [
  {
    "repo": "tabularis",
    "number": 896,
    "title": "[Bug]: In-app updater is not disabled for Homebrew and WinGet installs",
    "url": "https://github.com/TabularisDB/tabularis/issues/896",
    "labels": [
      {
        "name": "bug",
        "color": "d73a4a"
      },
      {
        "name": "help wanted",
        "color": "008672"
      }
    ],
    "kind": "bug",
    "assignees": [],
    "comments": 0,
    "createdAt": "2026-10-07T20:56:11Z"
  },
  {
    "repo": "tabularis",
    "number": 895,
    "title": "[Bug]: --debug does not enable debug logging (log level is hard-coded to Info)",
    "url": "https://github.com/TabularisDB/tabularis/issues/895",
    "labels": [
      {
        "name": "bug",
        "color": "d73a4a"
      },
      {
        "name": "good first issue",
        "color": "7057ff"
      }
    ],
    "kind": "bug",
    "assignees": [],
    "comments": 0,
    "createdAt": "2026-10-07T20:56:09Z"
  },
  {
    "repo": "tabularis",
    "number": 894,
    "title": "[Bug]: Visual Explain AI analysis is always in English when the language is set to Auto",
    "url": "https://github.com/TabularisDB/tabularis/issues/894",
    "labels": [
      {
        "name": "bug",
        "color": "d73a4a"
      },
      {
        "name": "good first issue",
        "color": "7057ff"
      }
    ],
    "kind": "bug",
    "assignees": [
      {
        "login": "princecherry9905",
        "avatarUrl": "https://avatars.githubusercontent.com/u/230962627?v=4"
      }
    ],
    "comments": 2,
    "createdAt": "2026-10-07T20:56:07Z"
  },
  {
    "repo": "tabularis",
    "number": 893,
    "title": "[Bug]: PostgreSQL overloaded functions: View Definition / Edit pick an arbitrary overload",
    "url": "https://github.com/TabularisDB/tabularis/issues/893",
    "labels": [
      {
        "name": "bug",
        "color": "d73a4a"
      },
      {
        "name": "help wanted",
        "color": "008672"
      }
    ],
    "kind": "bug",
    "assignees": [],
    "comments": 0,
    "createdAt": "2026-10-07T20:56:06Z"
  },
  {
    "repo": "tabularis",
    "number": 892,
    "title": "[Bug]: Plugin UI slots data-grid.toolbar.actions and sidebar.footer.actions receive an empty context",
    "url": "https://github.com/TabularisDB/tabularis/issues/892",
    "labels": [
      {
        "name": "bug",
        "color": "d73a4a"
      },
      {
        "name": "help wanted",
        "color": "008672"
      }
    ],
    "kind": "bug",
    "assignees": [],
    "comments": 0,
    "createdAt": "2026-10-07T20:56:04Z"
  },
  {
    "repo": "tabularis",
    "number": 891,
    "title": "[Bug]: create-plugin --with-ui does not add the ui_extensions entry to the manifest",
    "url": "https://github.com/TabularisDB/tabularis/issues/891",
    "labels": [
      {
        "name": "bug",
        "color": "d73a4a"
      },
      {
        "name": "good first issue",
        "color": "7057ff"
      }
    ],
    "kind": "bug",
    "assignees": [
      {
        "login": "princecherry9905",
        "avatarUrl": "https://avatars.githubusercontent.com/u/230962627?v=4"
      }
    ],
    "comments": 2,
    "createdAt": "2026-10-07T20:56:02Z"
  },
  {
    "repo": "tabularis",
    "number": 890,
    "title": "[Bug]: create-plugin scaffold's not-implemented error bypasses the host fallbacks",
    "url": "https://github.com/TabularisDB/tabularis/issues/890",
    "labels": [
      {
        "name": "bug",
        "color": "d73a4a"
      },
      {
        "name": "good first issue",
        "color": "7057ff"
      }
    ],
    "kind": "bug",
    "assignees": [],
    "comments": 0,
    "createdAt": "2026-10-07T20:56:00Z"
  },
  {
    "repo": "tabularis",
    "number": 889,
    "title": "[Bug]: Trigger editor: multi-event SQL invalid on MySQL/SQLite, non-atomic edit can lose the trigger",
    "url": "https://github.com/TabularisDB/tabularis/issues/889",
    "labels": [
      {
        "name": "bug",
        "color": "d73a4a"
      },
      {
        "name": "help wanted",
        "color": "008672"
      }
    ],
    "kind": "bug",
    "assignees": [],
    "comments": 0,
    "createdAt": "2026-10-07T20:55:58Z"
  },
  {
    "repo": "tabularis",
    "number": 888,
    "title": "[Bug]: No \"New routine\" button for PostgreSQL schemas and MySQL multi-database connections",
    "url": "https://github.com/TabularisDB/tabularis/issues/888",
    "labels": [
      {
        "name": "bug",
        "color": "d73a4a"
      },
      {
        "name": "good first issue",
        "color": "7057ff"
      }
    ],
    "kind": "bug",
    "assignees": [],
    "comments": 0,
    "createdAt": "2026-10-07T20:55:57Z"
  },
  {
    "repo": "tabularis",
    "number": 887,
    "title": "[Bug]: \"Run…\" on a stored routine executes immediately instead of opening the SQL for review",
    "url": "https://github.com/TabularisDB/tabularis/issues/887",
    "labels": [
      {
        "name": "bug",
        "color": "d73a4a"
      },
      {
        "name": "good first issue",
        "color": "7057ff"
      }
    ],
    "kind": "bug",
    "assignees": [],
    "comments": 0,
    "createdAt": "2026-10-07T20:55:55Z"
  },
  {
    "repo": "tabularis",
    "number": 886,
    "title": "[Bug]: Kubernetes port-forward tunnels are never stopped or health-checked",
    "url": "https://github.com/TabularisDB/tabularis/issues/886",
    "labels": [
      {
        "name": "bug",
        "color": "d73a4a"
      },
      {
        "name": "help wanted",
        "color": "008672"
      }
    ],
    "kind": "bug",
    "assignees": [],
    "comments": 0,
    "createdAt": "2026-10-07T20:55:53Z"
  },
  {
    "repo": "tabularis",
    "number": 885,
    "title": "[Bug]: MCP one-click install writes the Claude Desktop config to the wrong folder on Windows",
    "url": "https://github.com/TabularisDB/tabularis/issues/885",
    "labels": [
      {
        "name": "bug",
        "color": "d73a4a"
      },
      {
        "name": "good first issue",
        "color": "7057ff"
      }
    ],
    "kind": "bug",
    "assignees": [],
    "comments": 0,
    "createdAt": "2026-10-07T20:55:52Z"
  },
  {
    "repo": "tabularis",
    "number": 884,
    "title": "[Bug]: Visual Explain enables ANALYZE by default for REPLACE, MERGE and data-modifying CTEs",
    "url": "https://github.com/TabularisDB/tabularis/issues/884",
    "labels": [
      {
        "name": "bug",
        "color": "d73a4a"
      },
      {
        "name": "good first issue",
        "color": "7057ff"
      }
    ],
    "kind": "bug",
    "assignees": [],
    "comments": 0,
    "createdAt": "2026-10-07T20:55:50Z"
  },
  {
    "repo": "tabularis",
    "number": 883,
    "title": "[Bug]: Column masking, sticky headers and some grid settings are lost on restart",
    "url": "https://github.com/TabularisDB/tabularis/issues/883",
    "labels": [
      {
        "name": "bug",
        "color": "d73a4a"
      },
      {
        "name": "good first issue",
        "color": "7057ff"
      }
    ],
    "kind": "bug",
    "assignees": [],
    "comments": 0,
    "createdAt": "2026-10-07T20:55:49Z"
  },
  {
    "repo": "tabularis",
    "number": 879,
    "title": "[Bug]: Stable AppImage ships AppRun.wrapped as 0770, fails under firejail / AppImage catalog test",
    "url": "https://github.com/TabularisDB/tabularis/issues/879",
    "labels": [
      {
        "name": "bug",
        "color": "d73a4a"
      }
    ],
    "kind": "bug",
    "assignees": [],
    "comments": 0,
    "createdAt": "2026-10-07T14:34:32Z"
  },
  {
    "repo": "tabularis",
    "number": 876,
    "title": "[Feat]: Drag & drop connections into groups & sidebar group organization",
    "url": "https://github.com/TabularisDB/tabularis/issues/876",
    "labels": [
      {
        "name": "feature request",
        "color": "02637c"
      }
    ],
    "kind": "feature",
    "assignees": [
      {
        "login": "benedettoraviotta",
        "avatarUrl": "https://avatars.githubusercontent.com/u/59974565?v=4"
      }
    ],
    "comments": 2,
    "createdAt": "2026-10-07T10:08:07Z"
  },
  {
    "repo": "tabularis",
    "number": 873,
    "title": "Update the logo across the app: icons, dock, installers and in-app branding",
    "url": "https://github.com/TabularisDB/tabularis/issues/873",
    "labels": [
      {
        "name": "enhancement",
        "color": "a2eeef"
      }
    ],
    "kind": "feature",
    "assignees": [
      {
        "login": "wajrock",
        "avatarUrl": "https://avatars.githubusercontent.com/u/157038485?v=4"
      }
    ],
    "comments": 0,
    "createdAt": "2026-10-06T18:51:20Z"
  },
  {
    "repo": "tabularis",
    "number": 871,
    "title": "[Feat]: Data grid: \"Jump to column\" quick picker",
    "url": "https://github.com/TabularisDB/tabularis/issues/871",
    "labels": [
      {
        "name": "help wanted",
        "color": "008672"
      },
      {
        "name": "feature request",
        "color": "02637c"
      }
    ],
    "kind": "feature",
    "assignees": [],
    "comments": 0,
    "createdAt": "2026-10-06T18:47:58Z"
  },
  {
    "repo": "tabularis",
    "number": 869,
    "title": "[Feat]: Structured filter: pick values from the column's distinct values",
    "url": "https://github.com/TabularisDB/tabularis/issues/869",
    "labels": [
      {
        "name": "help wanted",
        "color": "008672"
      },
      {
        "name": "feature request",
        "color": "02637c"
      }
    ],
    "kind": "feature",
    "assignees": [],
    "comments": 0,
    "createdAt": "2026-10-06T18:47:54Z"
  },
  {
    "repo": "tabularis",
    "number": 868,
    "title": "[Feat]: Table view: auto-refresh data on an interval",
    "url": "https://github.com/TabularisDB/tabularis/issues/868",
    "labels": [
      {
        "name": "help wanted",
        "color": "008672"
      },
      {
        "name": "feature request",
        "color": "02637c"
      }
    ],
    "kind": "feature",
    "assignees": [],
    "comments": 0,
    "createdAt": "2026-10-06T18:47:53Z"
  },
  {
    "repo": "tabularis",
    "number": 867,
    "title": "[Feat]: Desktop notification when a long-running query finishes",
    "url": "https://github.com/TabularisDB/tabularis/issues/867",
    "labels": [
      {
        "name": "good first issue",
        "color": "7057ff"
      },
      {
        "name": "feature request",
        "color": "02637c"
      }
    ],
    "kind": "feature",
    "assignees": [],
    "comments": 0,
    "createdAt": "2026-10-06T18:47:51Z"
  },
  {
    "repo": "tabularis",
    "number": 866,
    "title": "[Feat]: Reopen the last closed tab (Ctrl/Cmd+Shift+T)",
    "url": "https://github.com/TabularisDB/tabularis/issues/866",
    "labels": [
      {
        "name": "help wanted",
        "color": "008672"
      },
      {
        "name": "feature request",
        "color": "02637c"
      }
    ],
    "kind": "feature",
    "assignees": [],
    "comments": 0,
    "createdAt": "2026-10-06T18:47:50Z"
  },
  {
    "repo": "tabularis",
    "number": 865,
    "title": "[Feat]: Data grid: multi-column sort with Shift+click",
    "url": "https://github.com/TabularisDB/tabularis/issues/865",
    "labels": [
      {
        "name": "good first issue",
        "color": "7057ff"
      },
      {
        "name": "feature request",
        "color": "02637c"
      }
    ],
    "kind": "feature",
    "assignees": [],
    "comments": 0,
    "createdAt": "2026-10-06T18:47:48Z"
  },
  {
    "repo": "tabularis",
    "number": 864,
    "title": "[Feat]: Structured filter: Match all / Match any (AND/OR) toggle",
    "url": "https://github.com/TabularisDB/tabularis/issues/864",
    "labels": [
      {
        "name": "good first issue",
        "color": "7057ff"
      },
      {
        "name": "feature request",
        "color": "02637c"
      }
    ],
    "kind": "feature",
    "assignees": [],
    "comments": 0,
    "createdAt": "2026-10-06T18:47:46Z"
  },
  {
    "repo": "tabularis",
    "number": 863,
    "title": "[Feat]: Rosé Pine theme package (Dawn and Main)",
    "url": "https://github.com/TabularisDB/tabularis/issues/863",
    "labels": [
      {
        "name": "good first issue",
        "color": "7057ff"
      },
      {
        "name": "feature request",
        "color": "02637c"
      }
    ],
    "kind": "feature",
    "assignees": [],
    "comments": 0,
    "createdAt": "2026-10-06T18:44:58Z"
  },
  {
    "repo": "tabularis",
    "number": 862,
    "title": "[Feat]: Tokyo Night theme package (Day and Night)",
    "url": "https://github.com/TabularisDB/tabularis/issues/862",
    "labels": [
      {
        "name": "good first issue",
        "color": "7057ff"
      },
      {
        "name": "feature request",
        "color": "02637c"
      }
    ],
    "kind": "feature",
    "assignees": [],
    "comments": 0,
    "createdAt": "2026-10-06T18:44:57Z"
  },
  {
    "repo": "tabularis",
    "number": 861,
    "title": "[Feat]: Catppuccin theme package (Latte and Mocha)",
    "url": "https://github.com/TabularisDB/tabularis/issues/861",
    "labels": [
      {
        "name": "good first issue",
        "color": "7057ff"
      },
      {
        "name": "feature request",
        "color": "02637c"
      }
    ],
    "kind": "feature",
    "assignees": [],
    "comments": 0,
    "createdAt": "2026-10-06T18:44:55Z"
  },
  {
    "repo": "tabularis",
    "number": 860,
    "title": "[Feat]: Connection string import: support JDBC URLs, credentials and sslmode in query parameters",
    "url": "https://github.com/TabularisDB/tabularis/issues/860",
    "labels": [
      {
        "name": "good first issue",
        "color": "7057ff"
      },
      {
        "name": "feature request",
        "color": "02637c"
      }
    ],
    "kind": "feature",
    "assignees": [],
    "comments": 0,
    "createdAt": "2026-10-06T18:44:53Z"
  },
  {
    "repo": "tabularis",
    "number": 859,
    "title": "[Feat]: Query history: filter by outcome and time range",
    "url": "https://github.com/TabularisDB/tabularis/issues/859",
    "labels": [
      {
        "name": "good first issue",
        "color": "7057ff"
      },
      {
        "name": "feature request",
        "color": "02637c"
      }
    ],
    "kind": "feature",
    "assignees": [],
    "comments": 0,
    "createdAt": "2026-10-06T18:44:52Z"
  },
  {
    "repo": "tabularis",
    "number": 858,
    "title": "[Feat]: Setting for the case of keywords inserted by autocomplete",
    "url": "https://github.com/TabularisDB/tabularis/issues/858",
    "labels": [
      {
        "name": "good first issue",
        "color": "7057ff"
      },
      {
        "name": "feature request",
        "color": "02637c"
      }
    ],
    "kind": "feature",
    "assignees": [
      {
        "login": "njtherealss",
        "avatarUrl": "https://avatars.githubusercontent.com/u/338089768?v=4"
      }
    ],
    "comments": 2,
    "createdAt": "2026-10-06T18:44:50Z"
  },
  {
    "repo": "tabularis",
    "number": 857,
    "title": "[Feat]: Duplicate editor tab from the tab context menu",
    "url": "https://github.com/TabularisDB/tabularis/issues/857",
    "labels": [
      {
        "name": "good first issue",
        "color": "7057ff"
      },
      {
        "name": "feature request",
        "color": "02637c"
      }
    ],
    "kind": "feature",
    "assignees": [],
    "comments": 0,
    "createdAt": "2026-10-06T18:44:48Z"
  },
  {
    "repo": "tabularis",
    "number": 856,
    "title": "[Feat]: Data grid: selection summary (count, sum, avg, min, max) for selected cells",
    "url": "https://github.com/TabularisDB/tabularis/issues/856",
    "labels": [
      {
        "name": "good first issue",
        "color": "7057ff"
      },
      {
        "name": "feature request",
        "color": "02637c"
      }
    ],
    "kind": "feature",
    "assignees": [],
    "comments": 0,
    "createdAt": "2026-10-06T18:44:46Z"
  },
  {
    "repo": "tabularis",
    "number": 854,
    "title": "[Feat]: Data grid: optional alternating row background (zebra stripes)",
    "url": "https://github.com/TabularisDB/tabularis/issues/854",
    "labels": [
      {
        "name": "good first issue",
        "color": "7057ff"
      },
      {
        "name": "feature request",
        "color": "02637c"
      }
    ],
    "kind": "feature",
    "assignees": [],
    "comments": 0,
    "createdAt": "2026-10-06T18:44:42Z"
  },
  {
    "repo": "tabularis",
    "number": 853,
    "title": "[Feat]: \"Filter by this value\" in the data grid cell context menu",
    "url": "https://github.com/TabularisDB/tabularis/issues/853",
    "labels": [
      {
        "name": "good first issue",
        "color": "7057ff"
      },
      {
        "name": "feature request",
        "color": "02637c"
      }
    ],
    "kind": "feature",
    "assignees": [],
    "comments": 0,
    "createdAt": "2026-10-06T18:44:40Z"
  },
  {
    "repo": "tabularis",
    "number": 852,
    "title": "[Feat]: Filter bar: contains, starts with, ends with, is empty operators for text columns",
    "url": "https://github.com/TabularisDB/tabularis/issues/852",
    "labels": [
      {
        "name": "good first issue",
        "color": "7057ff"
      },
      {
        "name": "feature request",
        "color": "02637c"
      }
    ],
    "kind": "feature",
    "assignees": [],
    "comments": 0,
    "createdAt": "2026-10-06T18:44:39Z"
  },
  {
    "repo": "tabularis-sqlserver-plugin",
    "number": 37,
    "title": "Runtime errors in a batch surface as \"Expected ColumnMetadata in context\" (mssql-tds-preview drain_stream)",
    "url": "https://github.com/TabularisDB/tabularis-sqlserver-plugin/issues/37",
    "labels": [],
    "kind": null,
    "assignees": [],
    "comments": 0,
    "createdAt": "2026-10-06T06:03:08Z"
  },
  {
    "repo": "tabularis",
    "number": 844,
    "title": "[Bug]: Fixed column width",
    "url": "https://github.com/TabularisDB/tabularis/issues/844",
    "labels": [
      {
        "name": "bug",
        "color": "d73a4a"
      }
    ],
    "kind": "bug",
    "assignees": [],
    "comments": 1,
    "createdAt": "2026-10-02T12:43:52Z"
  },
  {
    "repo": "tabularis-postgresql-plugin",
    "number": 129,
    "title": "[Bug]: DB is not able to export using the new PostgreSQL plugin",
    "url": "https://github.com/TabularisDB/tabularis-postgresql-plugin/issues/129",
    "labels": [
      {
        "name": "bug",
        "color": "d73a4a"
      }
    ],
    "kind": "bug",
    "assignees": [
      {
        "login": "aesslinger",
        "avatarUrl": "https://avatars.githubusercontent.com/u/14128427?v=4"
      }
    ],
    "comments": 2,
    "createdAt": "2026-09-30T14:00:07Z"
  },
  {
    "repo": "tabularis",
    "number": 840,
    "title": "Generate SQL / Create Table / column display drops type fidelity: serial width, composite FKs, numeric precision, VARCHAR length",
    "url": "https://github.com/TabularisDB/tabularis/issues/840",
    "labels": [],
    "kind": null,
    "assignees": [],
    "comments": 0,
    "createdAt": "2026-09-30T11:41:23Z"
  },
  {
    "repo": "tabularis",
    "number": 839,
    "title": "[Feat]: UI actions to create a database and a schema on a server-based connection",
    "url": "https://github.com/TabularisDB/tabularis/issues/839",
    "labels": [],
    "kind": null,
    "assignees": [],
    "comments": 0,
    "createdAt": "2026-09-29T13:50:29Z"
  },
  {
    "repo": "tabularis",
    "number": 837,
    "title": "[Bug]: Create Trigger modal generates invalid PostgreSQL syntax (MySQL-style BEGIN/END body)",
    "url": "https://github.com/TabularisDB/tabularis/issues/837",
    "labels": [],
    "kind": null,
    "assignees": [
      {
        "login": "aesslinger",
        "avatarUrl": "https://avatars.githubusercontent.com/u/14128427?v=4"
      }
    ],
    "comments": 2,
    "createdAt": "2026-09-29T12:38:58Z"
  },
  {
    "repo": "tabularis-oracle-plugin",
    "number": 12,
    "title": "RUSTSEC-2024-0436: paste - no longer maintained",
    "url": "https://github.com/TabularisDB/tabularis-oracle-plugin/issues/12",
    "labels": [],
    "kind": null,
    "assignees": [],
    "comments": 0,
    "createdAt": "2026-09-29T11:27:47Z"
  },
  {
    "repo": "tabularis",
    "number": 827,
    "title": "[Feat]: Database Features: Empty, Truncate, Drop, etc.",
    "url": "https://github.com/TabularisDB/tabularis/issues/827",
    "labels": [
      {
        "name": "feature request",
        "color": "02637c"
      }
    ],
    "kind": "feature",
    "assignees": [],
    "comments": 1,
    "createdAt": "2026-09-27T08:57:04Z"
  },
  {
    "repo": "tabularis",
    "number": 820,
    "title": "[Feat]: Ask for the password if unset instead of throwing a configuration error",
    "url": "https://github.com/TabularisDB/tabularis/issues/820",
    "labels": [
      {
        "name": "feature request",
        "color": "02637c"
      }
    ],
    "kind": "feature",
    "assignees": [],
    "comments": 3,
    "createdAt": "2026-09-25T08:01:09Z"
  },
  {
    "repo": "tabularis-dynamodb-plugin",
    "number": 91,
    "title": "`test_deep.py`'s is_nullable note is a false positive — a sort key is not `is_pk`",
    "url": "https://github.com/TabularisDB/tabularis-dynamodb-plugin/issues/91",
    "labels": [
      {
        "name": "bug",
        "color": "d73a4a"
      },
      {
        "name": "priority:low",
        "color": "c5def5"
      },
      {
        "name": "area:tests",
        "color": "5319e7"
      }
    ],
    "kind": "bug",
    "assignees": [],
    "comments": 0,
    "createdAt": "2026-09-21T14:22:14Z"
  },
  {
    "repo": "tabularis-dynamodb-plugin",
    "number": 90,
    "title": "`test_deep.py` reports 'no validation of key columns' even though the plugin rejects them",
    "url": "https://github.com/TabularisDB/tabularis-dynamodb-plugin/issues/90",
    "labels": [
      {
        "name": "bug",
        "color": "d73a4a"
      },
      {
        "name": "priority:low",
        "color": "c5def5"
      },
      {
        "name": "area:tests",
        "color": "5319e7"
      }
    ],
    "kind": "bug",
    "assignees": [],
    "comments": 0,
    "createdAt": "2026-09-21T14:22:12Z"
  },
  {
    "repo": "tabularis-dynamodb-plugin",
    "number": 89,
    "title": "README's `#!scan`/`#!query` examples use fields the native-body parser ignores — the scan filter is silently dropped",
    "url": "https://github.com/TabularisDB/tabularis-dynamodb-plugin/issues/89",
    "labels": [
      {
        "name": "bug",
        "color": "d73a4a"
      },
      {
        "name": "area:query",
        "color": "0e8a16"
      },
      {
        "name": "priority:high",
        "color": "b60205"
      },
      {
        "name": "area:docs",
        "color": "d4c5f9"
      }
    ],
    "kind": "bug",
    "assignees": [],
    "comments": 0,
    "createdAt": "2026-09-21T14:22:10Z"
  },
  {
    "repo": "tabularis",
    "number": 792,
    "title": "[Feat]: Allow sqlite via SSH tunnel",
    "url": "https://github.com/TabularisDB/tabularis/issues/792",
    "labels": [
      {
        "name": "feature request",
        "color": "02637c"
      }
    ],
    "kind": "feature",
    "assignees": [],
    "comments": 2,
    "createdAt": "2026-09-19T06:35:25Z"
  },
  {
    "repo": "tabularis",
    "number": 788,
    "title": "Plugin driver shutdown kills in-flight requests instead of draining them",
    "url": "https://github.com/TabularisDB/tabularis/issues/788",
    "labels": [],
    "kind": null,
    "assignees": [],
    "comments": 0,
    "createdAt": "2026-09-18T16:54:24Z"
  },
  {
    "repo": "tabularis",
    "number": 771,
    "title": "Feature proposal: share connections and their credentials with a team, through an encrypted vault on a shared folder",
    "url": "https://github.com/TabularisDB/tabularis/issues/771",
    "labels": [],
    "kind": null,
    "assignees": [],
    "comments": 4,
    "createdAt": "2026-09-16T07:14:43Z"
  },
  {
    "repo": "tabularis",
    "number": 757,
    "title": "[Feat]: Support encrypted SQLite (SQLCipher)",
    "url": "https://github.com/TabularisDB/tabularis/issues/757",
    "labels": [
      {
        "name": "feature request",
        "color": "02637c"
      }
    ],
    "kind": "feature",
    "assignees": [],
    "comments": 0,
    "createdAt": "2026-09-13T13:36:14Z"
  },
  {
    "repo": "tabularis",
    "number": 753,
    "title": "[Feat]: Built-in SSH tunnel profiles (jumphost, -L/-D forwards, SOCKS)",
    "url": "https://github.com/TabularisDB/tabularis/issues/753",
    "labels": [
      {
        "name": "feature request",
        "color": "02637c"
      }
    ],
    "kind": "feature",
    "assignees": [],
    "comments": 1,
    "createdAt": "2026-09-13T05:14:36Z"
  },
  {
    "repo": "tabularis",
    "number": 752,
    "title": "[Bug]: Redis multi-DB connection — sidebar DB selection not passed to plugin (queries always run on DB 0)",
    "url": "https://github.com/TabularisDB/tabularis/issues/752",
    "labels": [
      {
        "name": "bug",
        "color": "d73a4a"
      }
    ],
    "kind": "bug",
    "assignees": [],
    "comments": 0,
    "createdAt": "2026-09-13T05:07:09Z"
  },
  {
    "repo": "tabularis",
    "number": 733,
    "title": "[Bug]: Few library warning while opening the .appimage at command line",
    "url": "https://github.com/TabularisDB/tabularis/issues/733",
    "labels": [
      {
        "name": "bug",
        "color": "d73a4a"
      }
    ],
    "kind": "bug",
    "assignees": [],
    "comments": 0,
    "createdAt": "2026-09-10T08:11:26Z"
  },
  {
    "repo": "tabularis",
    "number": 725,
    "title": "[Feat]: Feature request — PostgreSQL: allow connecting without a specific database and show/select all databases (like MySQL)",
    "url": "https://github.com/TabularisDB/tabularis/issues/725",
    "labels": [
      {
        "name": "feature request",
        "color": "02637c"
      }
    ],
    "kind": "feature",
    "assignees": [],
    "comments": 1,
    "createdAt": "2026-09-07T09:31:38Z"
  },
  {
    "repo": "tabularis-csv-plugin",
    "number": 4,
    "title": "Page size defaults to 100",
    "url": "https://github.com/TabularisDB/tabularis-csv-plugin/issues/4",
    "labels": [],
    "kind": null,
    "assignees": [],
    "comments": 1,
    "createdAt": "2026-09-04T21:23:42Z"
  },
  {
    "repo": "tabularis",
    "number": 714,
    "title": "Frontend still duplicates postgres-specific config across 4 places; next driver deprecation needs manual edits, not a config entry",
    "url": "https://github.com/TabularisDB/tabularis/issues/714",
    "labels": [],
    "kind": null,
    "assignees": [],
    "comments": 0,
    "createdAt": "2026-09-04T13:28:23Z"
  },
  {
    "repo": "tabularis",
    "number": 709,
    "title": "[Feat]: Export a single table to SQL from the context menu and import it into a connection of the same type",
    "url": "https://github.com/TabularisDB/tabularis/issues/709",
    "labels": [
      {
        "name": "enhancement",
        "color": "a2eeef"
      },
      {
        "name": "feature request",
        "color": "02637c"
      }
    ],
    "kind": "feature",
    "assignees": [],
    "comments": 0,
    "createdAt": "2026-09-03T15:31:21Z"
  },
  {
    "repo": "tabularis-duckdb-plugin",
    "number": 6,
    "title": "datatype Date presented as int",
    "url": "https://github.com/TabularisDB/tabularis-duckdb-plugin/issues/6",
    "labels": [],
    "kind": null,
    "assignees": [],
    "comments": 2,
    "createdAt": "2026-09-03T13:19:00Z"
  },
  {
    "repo": "tabularis",
    "number": 698,
    "title": "[Feat]: Allow editing SQLite string BLOBs",
    "url": "https://github.com/TabularisDB/tabularis/issues/698",
    "labels": [
      {
        "name": "feature request",
        "color": "02637c"
      }
    ],
    "kind": "feature",
    "assignees": [],
    "comments": 2,
    "createdAt": "2026-08-31T19:10:24Z"
  },
  {
    "repo": "tabularis-postgresql-plugin",
    "number": 58,
    "title": "Support AWS IAM authentication for PostgreSQL connections (RDS)",
    "url": "https://github.com/TabularisDB/tabularis-postgresql-plugin/issues/58",
    "labels": [
      {
        "name": "enhancement",
        "color": "a2eeef"
      }
    ],
    "kind": "feature",
    "assignees": [
      {
        "login": "aesslinger",
        "avatarUrl": "https://avatars.githubusercontent.com/u/14128427?v=4"
      }
    ],
    "comments": 0,
    "createdAt": "2026-08-31T14:24:22Z"
  },
  {
    "repo": "tabularis",
    "number": 694,
    "title": "[Feat]: Support AWS IAM also for PostgresDB connections",
    "url": "https://github.com/TabularisDB/tabularis/issues/694",
    "labels": [
      {
        "name": "feature request",
        "color": "02637c"
      }
    ],
    "kind": "feature",
    "assignees": [],
    "comments": 2,
    "createdAt": "2026-08-31T11:21:21Z"
  },
  {
    "repo": "tabularis",
    "number": 693,
    "title": "[Feat]: Show (some) integers as timestamp strings",
    "url": "https://github.com/TabularisDB/tabularis/issues/693",
    "labels": [
      {
        "name": "feature request",
        "color": "02637c"
      }
    ],
    "kind": "feature",
    "assignees": [],
    "comments": 0,
    "createdAt": "2026-08-31T10:55:03Z"
  },
  {
    "repo": "tabularis",
    "number": 692,
    "title": "[Feat]: Default Database selection.",
    "url": "https://github.com/TabularisDB/tabularis/issues/692",
    "labels": [
      {
        "name": "feature request",
        "color": "02637c"
      }
    ],
    "kind": "feature",
    "assignees": [],
    "comments": 0,
    "createdAt": "2026-08-31T10:21:42Z"
  },
  {
    "repo": "tabularis",
    "number": 690,
    "title": "[Feat]: Add edit in query results view",
    "url": "https://github.com/TabularisDB/tabularis/issues/690",
    "labels": [
      {
        "name": "feature request",
        "color": "02637c"
      }
    ],
    "kind": "feature",
    "assignees": [],
    "comments": 3,
    "createdAt": "2026-08-31T07:47:41Z"
  },
  {
    "repo": "tabularis",
    "number": 686,
    "title": "[Feat]: Optional Vim keybindings (modal editing) in the Monaco editor",
    "url": "https://github.com/TabularisDB/tabularis/issues/686",
    "labels": [
      {
        "name": "feature request",
        "color": "02637c"
      }
    ],
    "kind": "feature",
    "assignees": [],
    "comments": 0,
    "createdAt": "2026-08-28T23:20:50Z"
  },
  {
    "repo": "tabularis-postgresql-plugin",
    "number": 51,
    "title": "Improve schema search_path handling (overwrite → append/prepend)",
    "url": "https://github.com/TabularisDB/tabularis-postgresql-plugin/issues/51",
    "labels": [
      {
        "name": "enhancement",
        "color": "a2eeef"
      }
    ],
    "kind": "feature",
    "assignees": [
      {
        "login": "aesslinger",
        "avatarUrl": "https://avatars.githubusercontent.com/u/14128427?v=4"
      }
    ],
    "comments": 3,
    "createdAt": "2026-08-21T12:28:56Z"
  },
  {
    "repo": "tabularis-postgresql-plugin",
    "number": 32,
    "title": "Phase 2.8: Wire up stubbed batch/snapshot RPC methods",
    "url": "https://github.com/TabularisDB/tabularis-postgresql-plugin/issues/32",
    "labels": [
      {
        "name": "enhancement",
        "color": "a2eeef"
      }
    ],
    "kind": "feature",
    "assignees": [
      {
        "login": "aesslinger",
        "avatarUrl": "https://avatars.githubusercontent.com/u/14128427?v=4"
      }
    ],
    "comments": 0,
    "createdAt": "2026-08-18T15:46:58Z"
  },
  {
    "repo": "tabularis-postgresql-plugin",
    "number": 31,
    "title": "Phase 2.7: Advisory lock monitoring",
    "url": "https://github.com/TabularisDB/tabularis-postgresql-plugin/issues/31",
    "labels": [
      {
        "name": "enhancement",
        "color": "a2eeef"
      }
    ],
    "kind": "feature",
    "assignees": [
      {
        "login": "aesslinger",
        "avatarUrl": "https://avatars.githubusercontent.com/u/14128427?v=4"
      }
    ],
    "comments": 0,
    "createdAt": "2026-08-18T15:46:48Z"
  },
  {
    "repo": "tabularis-postgresql-plugin",
    "number": 30,
    "title": "Phase 2.6: Publication/subscription visibility",
    "url": "https://github.com/TabularisDB/tabularis-postgresql-plugin/issues/30",
    "labels": [
      {
        "name": "enhancement",
        "color": "a2eeef"
      }
    ],
    "kind": "feature",
    "assignees": [
      {
        "login": "aesslinger",
        "avatarUrl": "https://avatars.githubusercontent.com/u/14128427?v=4"
      }
    ],
    "comments": 0,
    "createdAt": "2026-08-18T15:46:40Z"
  },
  {
    "repo": "tabularis-postgresql-plugin",
    "number": 29,
    "title": "Phase 2.5: Row-level security policy visibility",
    "url": "https://github.com/TabularisDB/tabularis-postgresql-plugin/issues/29",
    "labels": [
      {
        "name": "enhancement",
        "color": "a2eeef"
      }
    ],
    "kind": "feature",
    "assignees": [
      {
        "login": "aesslinger",
        "avatarUrl": "https://avatars.githubusercontent.com/u/14128427?v=4"
      }
    ],
    "comments": 0,
    "createdAt": "2026-08-18T15:46:32Z"
  },
  {
    "repo": "tabularis-postgresql-plugin",
    "number": 28,
    "title": "Phase 2.4: Partition table introspection",
    "url": "https://github.com/TabularisDB/tabularis-postgresql-plugin/issues/28",
    "labels": [
      {
        "name": "enhancement",
        "color": "a2eeef"
      }
    ],
    "kind": "feature",
    "assignees": [
      {
        "login": "aesslinger",
        "avatarUrl": "https://avatars.githubusercontent.com/u/14128427?v=4"
      }
    ],
    "comments": 0,
    "createdAt": "2026-08-18T15:46:23Z"
  },
  {
    "repo": "tabularis-postgresql-plugin",
    "number": 27,
    "title": "Phase 2.3: Extension-aware type system",
    "url": "https://github.com/TabularisDB/tabularis-postgresql-plugin/issues/27",
    "labels": [
      {
        "name": "enhancement",
        "color": "a2eeef"
      }
    ],
    "kind": "feature",
    "assignees": [
      {
        "login": "aesslinger",
        "avatarUrl": "https://avatars.githubusercontent.com/u/14128427?v=4"
      }
    ],
    "comments": 2,
    "createdAt": "2026-08-18T15:46:12Z"
  },
  {
    "repo": "tabularis-postgresql-plugin",
    "number": 26,
    "title": "Phase 2.2: JSONB inline editing",
    "url": "https://github.com/TabularisDB/tabularis-postgresql-plugin/issues/26",
    "labels": [
      {
        "name": "enhancement",
        "color": "a2eeef"
      }
    ],
    "kind": "feature",
    "assignees": [
      {
        "login": "aesslinger",
        "avatarUrl": "https://avatars.githubusercontent.com/u/14128427?v=4"
      }
    ],
    "comments": 0,
    "createdAt": "2026-08-18T15:46:02Z"
  },
  {
    "repo": "tabularis-postgresql-plugin",
    "number": 25,
    "title": "Phase 2.1: Sequence management",
    "url": "https://github.com/TabularisDB/tabularis-postgresql-plugin/issues/25",
    "labels": [
      {
        "name": "enhancement",
        "color": "a2eeef"
      }
    ],
    "kind": "feature",
    "assignees": [
      {
        "login": "aesslinger",
        "avatarUrl": "https://avatars.githubusercontent.com/u/14128427?v=4"
      }
    ],
    "comments": 0,
    "createdAt": "2026-08-18T15:45:51Z"
  },
  {
    "repo": "tabularis",
    "number": 653,
    "title": "[Feat]: Postgresql improve schema search_path",
    "url": "https://github.com/TabularisDB/tabularis/issues/653",
    "labels": [
      {
        "name": "feature request",
        "color": "02637c"
      }
    ],
    "kind": "feature",
    "assignees": [],
    "comments": 1,
    "createdAt": "2026-08-17T09:44:02Z"
  },
  {
    "repo": "tabularis",
    "number": 636,
    "title": "Integrate SignPath Authenticode signing into the Tauri Windows release pipeline",
    "url": "https://github.com/TabularisDB/tabularis/issues/636",
    "labels": [
      {
        "name": "feature request",
        "color": "02637c"
      }
    ],
    "kind": "feature",
    "assignees": [],
    "comments": 0,
    "createdAt": "2026-08-14T09:10:48Z"
  },
  {
    "repo": "tabularis",
    "number": 631,
    "title": "Phase 3: Deprecate built-in PostgreSQL driver (deferred decision)",
    "url": "https://github.com/TabularisDB/tabularis/issues/631",
    "labels": [],
    "kind": null,
    "assignees": [
      {
        "login": "aesslinger",
        "avatarUrl": "https://avatars.githubusercontent.com/u/14128427?v=4"
      }
    ],
    "comments": 1,
    "createdAt": "2026-08-13T12:33:56Z"
  },
  {
    "repo": "tabularis-postgresql-plugin",
    "number": 9,
    "title": "Phase 2: PostgreSQL-specific features beyond the built-in driver (tabularis#16)",
    "url": "https://github.com/TabularisDB/tabularis-postgresql-plugin/issues/9",
    "labels": [
      {
        "name": "enhancement",
        "color": "a2eeef"
      }
    ],
    "kind": "feature",
    "assignees": [
      {
        "login": "aesslinger",
        "avatarUrl": "https://avatars.githubusercontent.com/u/14128427?v=4"
      }
    ],
    "comments": 0,
    "createdAt": "2026-08-12T18:48:46Z"
  },
  {
    "repo": "tabularis-bigquery-plugin",
    "number": 1,
    "title": "[Plugin system]: support secure per-connection fields and customizable base fields",
    "url": "https://github.com/TabularisDB/tabularis-bigquery-plugin/issues/1",
    "labels": [],
    "kind": null,
    "assignees": [],
    "comments": 0,
    "createdAt": "2026-08-11T13:28:29Z"
  },
  {
    "repo": "tabularis-clickhouse-plugin",
    "number": 4,
    "title": "SHOW / DESCRIBE / DDL statements fail — plugin wraps every query in \"SELECT * FROM (…) LIMIT 501 OFFSET 0 FORMAT JSONEachRow\"",
    "url": "https://github.com/TabularisDB/tabularis-clickhouse-plugin/issues/4",
    "labels": [],
    "kind": null,
    "assignees": [],
    "comments": 1,
    "createdAt": "2026-08-04T15:37:52Z"
  },
  {
    "repo": "tabularis",
    "number": 592,
    "title": "[Feat]: Tabularis App Mobile",
    "url": "https://github.com/TabularisDB/tabularis/issues/592",
    "labels": [
      {
        "name": "feature request",
        "color": "02637c"
      }
    ],
    "kind": "feature",
    "assignees": [],
    "comments": 1,
    "createdAt": "2026-08-03T13:02:33Z"
  },
  {
    "repo": "tabularis",
    "number": 561,
    "title": "[Feat]: Transposed Datagrid View",
    "url": "https://github.com/TabularisDB/tabularis/issues/561",
    "labels": [
      {
        "name": "feature request",
        "color": "02637c"
      }
    ],
    "kind": "feature",
    "assignees": [],
    "comments": 3,
    "createdAt": "2026-07-28T22:05:05Z"
  },
  {
    "repo": "tabularis",
    "number": 534,
    "title": "[Feat]: Remember of app window's size and position",
    "url": "https://github.com/TabularisDB/tabularis/issues/534",
    "labels": [
      {
        "name": "good first issue",
        "color": "7057ff"
      },
      {
        "name": "feature request",
        "color": "02637c"
      }
    ],
    "kind": "feature",
    "assignees": [],
    "comments": 0,
    "createdAt": "2026-07-25T17:13:41Z"
  },
  {
    "repo": "tabularis",
    "number": 526,
    "title": "Recognize externally-dropped databases from driver errors and the health check",
    "url": "https://github.com/TabularisDB/tabularis/issues/526",
    "labels": [],
    "kind": null,
    "assignees": [
      {
        "login": "debba",
        "avatarUrl": "https://avatars.githubusercontent.com/u/3198901?v=4"
      }
    ],
    "comments": 0,
    "createdAt": "2026-07-24T13:42:54Z"
  },
  {
    "repo": "tabularis",
    "number": 516,
    "title": "[Bug]: Incorrect schema name when submit for changes",
    "url": "https://github.com/TabularisDB/tabularis/issues/516",
    "labels": [
      {
        "name": "bug",
        "color": "d73a4a"
      }
    ],
    "kind": "bug",
    "assignees": [],
    "comments": 2,
    "createdAt": "2026-07-23T06:11:14Z"
  },
  {
    "repo": "tabularis",
    "number": 506,
    "title": "[Feat]: SQL autocomplete — resolve CTEs and derived tables as column sources",
    "url": "https://github.com/TabularisDB/tabularis/issues/506",
    "labels": [],
    "kind": null,
    "assignees": [],
    "comments": 0,
    "createdAt": "2026-07-21T18:26:37Z"
  },
  {
    "repo": "tabularis",
    "number": 484,
    "title": "[Feat]: Import data from file (CSV/TSV/JSON)",
    "url": "https://github.com/TabularisDB/tabularis/issues/484",
    "labels": [],
    "kind": null,
    "assignees": [],
    "comments": 0,
    "createdAt": "2026-07-15T10:01:29Z"
  },
  {
    "repo": "tabularis",
    "number": 483,
    "title": "[Feat]: Export data with column anonymization",
    "url": "https://github.com/TabularisDB/tabularis/issues/483",
    "labels": [],
    "kind": null,
    "assignees": [],
    "comments": 1,
    "createdAt": "2026-07-15T09:05:20Z"
  },
  {
    "repo": "tabularis",
    "number": 460,
    "title": "[Feat]: Cross Connection Notebook",
    "url": "https://github.com/TabularisDB/tabularis/issues/460",
    "labels": [
      {
        "name": "feature request",
        "color": "02637c"
      }
    ],
    "kind": "feature",
    "assignees": [],
    "comments": 1,
    "createdAt": "2026-07-11T04:05:36Z"
  },
  {
    "repo": "tabularis",
    "number": 449,
    "title": "[Bug]: pgvector are not shown",
    "url": "https://github.com/TabularisDB/tabularis/issues/449",
    "labels": [
      {
        "name": "bug",
        "color": "d73a4a"
      }
    ],
    "kind": "bug",
    "assignees": [],
    "comments": 1,
    "createdAt": "2026-07-08T22:29:12Z"
  },
  {
    "repo": "tabularis",
    "number": 406,
    "title": "[Bug]: SSH Tunnel does not get closed if server is rebooted",
    "url": "https://github.com/TabularisDB/tabularis/issues/406",
    "labels": [
      {
        "name": "bug",
        "color": "d73a4a"
      }
    ],
    "kind": "bug",
    "assignees": [
      {
        "login": "debba",
        "avatarUrl": "https://avatars.githubusercontent.com/u/3198901?v=4"
      }
    ],
    "comments": 3,
    "createdAt": "2026-07-01T11:38:32Z"
  },
  {
    "repo": "tabularis",
    "number": 381,
    "title": "Proposal: paradigm-aware plugin surfaces via kind: driver + paradigms",
    "url": "https://github.com/TabularisDB/tabularis/issues/381",
    "labels": [],
    "kind": null,
    "assignees": [
      {
        "login": "NewtTheWolf",
        "avatarUrl": "https://avatars.githubusercontent.com/u/59208097?v=4"
      }
    ],
    "comments": 0,
    "createdAt": "2026-06-25T18:25:35Z"
  },
  {
    "repo": "tabularis",
    "number": 340,
    "title": "[Feat]: Browse/access all databases on same connection",
    "url": "https://github.com/TabularisDB/tabularis/issues/340",
    "labels": [
      {
        "name": "feature request",
        "color": "02637c"
      }
    ],
    "kind": "feature",
    "assignees": [],
    "comments": 2,
    "createdAt": "2026-06-19T16:28:06Z"
  },
  {
    "repo": "tabularis",
    "number": 339,
    "title": "[Feat]: compact table view request",
    "url": "https://github.com/TabularisDB/tabularis/issues/339",
    "labels": [
      {
        "name": "feature request",
        "color": "02637c"
      }
    ],
    "kind": "feature",
    "assignees": [],
    "comments": 4,
    "createdAt": "2026-06-19T14:35:43Z"
  },
  {
    "repo": "tabularis",
    "number": 338,
    "title": "[Feat]: Postgresql: display table partitions as nested under the parent",
    "url": "https://github.com/TabularisDB/tabularis/issues/338",
    "labels": [
      {
        "name": "feature request",
        "color": "02637c"
      }
    ],
    "kind": "feature",
    "assignees": [],
    "comments": 0,
    "createdAt": "2026-06-19T13:58:23Z"
  },
  {
    "repo": "tabularis",
    "number": 335,
    "title": "[Bug]: Error on Visual Query when \"user\" table is used (Postgres)",
    "url": "https://github.com/TabularisDB/tabularis/issues/335",
    "labels": [
      {
        "name": "bug",
        "color": "d73a4a"
      }
    ],
    "kind": "bug",
    "assignees": [],
    "comments": 2,
    "createdAt": "2026-06-19T03:25:16Z"
  },
  {
    "repo": "tabularis",
    "number": 316,
    "title": "External plugin host support gaps found while building a DM / Dameng driver",
    "url": "https://github.com/TabularisDB/tabularis/issues/316",
    "labels": [],
    "kind": null,
    "assignees": [],
    "comments": 7,
    "createdAt": "2026-06-10T03:06:09Z"
  },
  {
    "repo": "tabularis",
    "number": 308,
    "title": "[Feat]: Visual EXPLAIN Table view enhancements - Loops column, detachable window, and customizable column order",
    "url": "https://github.com/TabularisDB/tabularis/issues/308",
    "labels": [
      {
        "name": "feature request",
        "color": "02637c"
      }
    ],
    "kind": "feature",
    "assignees": [],
    "comments": 1,
    "createdAt": "2026-06-09T00:20:05Z"
  },
  {
    "repo": "tabularis",
    "number": 301,
    "title": "[Feat]: Read only connection limiter support",
    "url": "https://github.com/TabularisDB/tabularis/issues/301",
    "labels": [
      {
        "name": "feature request",
        "color": "02637c"
      }
    ],
    "kind": "feature",
    "assignees": [],
    "comments": 7,
    "createdAt": "2026-06-08T12:55:01Z"
  },
  {
    "repo": "tabularis",
    "number": 271,
    "title": "[Feat]: Allow Renaming of Columns",
    "url": "https://github.com/TabularisDB/tabularis/issues/271",
    "labels": [
      {
        "name": "feature request",
        "color": "02637c"
      }
    ],
    "kind": "feature",
    "assignees": [],
    "comments": 1,
    "createdAt": "2026-06-02T13:53:58Z"
  },
  {
    "repo": "tabularis",
    "number": 224,
    "title": "[Feat]: Feature Request: Support Web / H5 (HTML5) mode for server deployment and remote web management",
    "url": "https://github.com/TabularisDB/tabularis/issues/224",
    "labels": [
      {
        "name": "feature request",
        "color": "02637c"
      }
    ],
    "kind": "feature",
    "assignees": [],
    "comments": 2,
    "createdAt": "2026-05-19T09:24:12Z"
  },
  {
    "repo": "tabularis",
    "number": 205,
    "title": "Run All: paged result sets may be re-executed against later session state",
    "url": "https://github.com/TabularisDB/tabularis/issues/205",
    "labels": [],
    "kind": null,
    "assignees": [],
    "comments": 1,
    "createdAt": "2026-05-16T18:20:43Z"
  },
  {
    "repo": "tabularis",
    "number": 195,
    "title": "UI design system & visual identity — call for contributors",
    "url": "https://github.com/TabularisDB/tabularis/issues/195",
    "labels": [
      {
        "name": "enhancement",
        "color": "a2eeef"
      },
      {
        "name": "help wanted",
        "color": "008672"
      },
      {
        "name": "roadmap",
        "color": "1d76db"
      }
    ],
    "kind": "feature",
    "assignees": [],
    "comments": 5,
    "createdAt": "2026-05-14T09:30:36Z"
  },
  {
    "repo": "tabularis",
    "number": 190,
    "title": "[Bug]: MySQL + SSH reconnect issues after pc goes to sleep (Windows)",
    "url": "https://github.com/TabularisDB/tabularis/issues/190",
    "labels": [
      {
        "name": "bug",
        "color": "d73a4a"
      }
    ],
    "kind": "bug",
    "assignees": [],
    "comments": 3,
    "createdAt": "2026-05-12T10:44:41Z"
  },
  {
    "repo": "tabularis-db2-plugin",
    "number": 10,
    "title": "Verify: Routine support",
    "url": "https://github.com/TabularisDB/tabularis-db2-plugin/issues/10",
    "labels": [
      {
        "name": "bug",
        "color": "d73a4a"
      }
    ],
    "kind": "bug",
    "assignees": [],
    "comments": 0,
    "createdAt": "2026-04-14T21:54:38Z"
  },
  {
    "repo": "tabularis-db2-plugin",
    "number": 9,
    "title": "Verify: Foreign key management",
    "url": "https://github.com/TabularisDB/tabularis-db2-plugin/issues/9",
    "labels": [
      {
        "name": "bug",
        "color": "d73a4a"
      }
    ],
    "kind": "bug",
    "assignees": [],
    "comments": 0,
    "createdAt": "2026-04-14T21:54:36Z"
  },
  {
    "repo": "tabularis-db2-plugin",
    "number": 8,
    "title": "Verify: Index management",
    "url": "https://github.com/TabularisDB/tabularis-db2-plugin/issues/8",
    "labels": [
      {
        "name": "bug",
        "color": "d73a4a"
      }
    ],
    "kind": "bug",
    "assignees": [],
    "comments": 0,
    "createdAt": "2026-04-14T21:54:33Z"
  },
  {
    "repo": "tabularis-db2-plugin",
    "number": 7,
    "title": "Verify: View support",
    "url": "https://github.com/TabularisDB/tabularis-db2-plugin/issues/7",
    "labels": [
      {
        "name": "bug",
        "color": "d73a4a"
      }
    ],
    "kind": "bug",
    "assignees": [],
    "comments": 0,
    "createdAt": "2026-04-14T21:54:30Z"
  },
  {
    "repo": "tabularis-db2-plugin",
    "number": 6,
    "title": "Verify: DDL generation",
    "url": "https://github.com/TabularisDB/tabularis-db2-plugin/issues/6",
    "labels": [
      {
        "name": "bug",
        "color": "d73a4a"
      }
    ],
    "kind": "bug",
    "assignees": [],
    "comments": 0,
    "createdAt": "2026-04-14T21:54:27Z"
  },
  {
    "repo": "tabularis-db2-plugin",
    "number": 5,
    "title": "Verify: Delete record",
    "url": "https://github.com/TabularisDB/tabularis-db2-plugin/issues/5",
    "labels": [
      {
        "name": "bug",
        "color": "d73a4a"
      }
    ],
    "kind": "bug",
    "assignees": [],
    "comments": 0,
    "createdAt": "2026-04-14T21:54:24Z"
  },
  {
    "repo": "tabularis-db2-plugin",
    "number": 4,
    "title": "Verify: Update record",
    "url": "https://github.com/TabularisDB/tabularis-db2-plugin/issues/4",
    "labels": [
      {
        "name": "bug",
        "color": "d73a4a"
      }
    ],
    "kind": "bug",
    "assignees": [],
    "comments": 2,
    "createdAt": "2026-04-14T21:54:22Z"
  },
  {
    "repo": "tabularis-db2-plugin",
    "number": 3,
    "title": "Verify: Insert record",
    "url": "https://github.com/TabularisDB/tabularis-db2-plugin/issues/3",
    "labels": [
      {
        "name": "bug",
        "color": "d73a4a"
      }
    ],
    "kind": "bug",
    "assignees": [],
    "comments": 0,
    "createdAt": "2026-04-14T21:54:19Z"
  },
  {
    "repo": "tabularis-db2-plugin",
    "number": 2,
    "title": "Verify: Query execution",
    "url": "https://github.com/TabularisDB/tabularis-db2-plugin/issues/2",
    "labels": [
      {
        "name": "bug",
        "color": "d73a4a"
      }
    ],
    "kind": "bug",
    "assignees": [],
    "comments": 0,
    "createdAt": "2026-04-14T21:54:16Z"
  },
  {
    "repo": "tabularis-db2-plugin",
    "number": 1,
    "title": "Verify: Schema & object browsing",
    "url": "https://github.com/TabularisDB/tabularis-db2-plugin/issues/1",
    "labels": [
      {
        "name": "bug",
        "color": "d73a4a"
      }
    ],
    "kind": "bug",
    "assignees": [],
    "comments": 0,
    "createdAt": "2026-04-14T21:54:13Z"
  },
  {
    "repo": "tabularis",
    "number": 97,
    "title": "[Bug]: Editor resets when I switch tabs",
    "url": "https://github.com/TabularisDB/tabularis/issues/97",
    "labels": [
      {
        "name": "bug",
        "color": "d73a4a"
      }
    ],
    "kind": "bug",
    "assignees": [],
    "comments": 7,
    "createdAt": "2026-03-17T08:04:10Z"
  },
  {
    "repo": "tabularis",
    "number": 79,
    "title": "[Feat]: transparant background on icon in windows",
    "url": "https://github.com/TabularisDB/tabularis/issues/79",
    "labels": [
      {
        "name": "feature request",
        "color": "02637c"
      }
    ],
    "kind": "feature",
    "assignees": [],
    "comments": 4,
    "createdAt": "2026-03-09T11:32:26Z"
  },
  {
    "repo": "tabularis",
    "number": 48,
    "title": "[Feat]: Render columns based on column size instead of only types",
    "url": "https://github.com/TabularisDB/tabularis/issues/48",
    "labels": [
      {
        "name": "feature request",
        "color": "02637c"
      }
    ],
    "kind": "feature",
    "assignees": [
      {
        "login": "debba",
        "avatarUrl": "https://avatars.githubusercontent.com/u/3198901?v=4"
      }
    ],
    "comments": 6,
    "createdAt": "2026-03-02T17:09:08Z"
  },
  {
    "repo": "tabularis",
    "number": 46,
    "title": "Feature: Remote Control",
    "url": "https://github.com/TabularisDB/tabularis/issues/46",
    "labels": [
      {
        "name": "enhancement",
        "color": "a2eeef"
      },
      {
        "name": "roadmap",
        "color": "1d76db"
      }
    ],
    "kind": "feature",
    "assignees": [
      {
        "login": "debba",
        "avatarUrl": "https://avatars.githubusercontent.com/u/3198901?v=4"
      }
    ],
    "comments": 0,
    "createdAt": "2026-02-27T18:03:40Z"
  },
  {
    "repo": "tabularis",
    "number": 21,
    "title": "Data Compare / Diff Tool",
    "url": "https://github.com/TabularisDB/tabularis/issues/21",
    "labels": [
      {
        "name": "enhancement",
        "color": "a2eeef"
      },
      {
        "name": "roadmap",
        "color": "1d76db"
      }
    ],
    "kind": "feature",
    "assignees": [],
    "comments": 5,
    "createdAt": "2026-02-10T07:45:53Z"
  },
  {
    "repo": "tabularis",
    "number": 20,
    "title": "Team Collaboration",
    "url": "https://github.com/TabularisDB/tabularis/issues/20",
    "labels": [
      {
        "name": "enhancement",
        "color": "a2eeef"
      },
      {
        "name": "roadmap",
        "color": "1d76db"
      }
    ],
    "kind": "feature",
    "assignees": [],
    "comments": 0,
    "createdAt": "2026-02-10T07:40:15Z"
  },
  {
    "repo": "tabularis",
    "number": 17,
    "title": "Better SQLite Support",
    "url": "https://github.com/TabularisDB/tabularis/issues/17",
    "labels": [
      {
        "name": "enhancement",
        "color": "a2eeef"
      },
      {
        "name": "roadmap",
        "color": "1d76db"
      }
    ],
    "kind": "feature",
    "assignees": [],
    "comments": 2,
    "createdAt": "2026-02-10T07:40:10Z"
  },
  {
    "repo": "tabularis",
    "number": 16,
    "title": "Better PostgreSQL Support",
    "url": "https://github.com/TabularisDB/tabularis/issues/16",
    "labels": [
      {
        "name": "enhancement",
        "color": "a2eeef"
      },
      {
        "name": "roadmap",
        "color": "1d76db"
      }
    ],
    "kind": "feature",
    "assignees": [],
    "comments": 5,
    "createdAt": "2026-02-10T07:40:08Z"
  }
];
